#!/usr/bin/env python
# coding: utf-8

import unittest
import difflib
from biopandas.pdb import PandasPdb
import numpy as np
import os


def get_sequence(ppdb_code):
    ppdb = PandasPdb().fetch_pdb(ppdb_code)
    amino_acid_sequence = ppdb.amino3to1().residue_name
    amino_acid_sequence = ''.join(amino_acid_sequence)
    return amino_acid_sequence

class TestGetSequence(unittest.TestCase):

    def test_get_sequence(self):
        
        protein_codes = ["1L2Y", "1UBQ", "2GB1", "1CTF", "4HHB", "1HRC", "3KUY", "1YCR", "2W5I", "2LZM", "2BG9",]
        expected_sequences = [
            "NLYIQWLKDGGPSSGRPPPS",
            "MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGG",
            "MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYDDATKTFTVTE",
            "AAEEKTEFDVILKAAGANKVAVIKAVRGATGLGLKEAKDLVESAPAALKEGVSKDDAEALKKALEEAGAEVEVK",
            "VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYRVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH",
            "XGDVEKGKKIFVQKCAQCHTVEKGGKHKTGPNLHGLFGRKTGQAPGFTYTDANKNKGITWKEETLMEYLENPKKYIPGTKMIFAGIKKKTEREDLIAYLKKATNE",
            "PEPAKSAPAPKKGSKKAVTKTQKKDGKKRRKTRKESYAIYVYKVLKQVHPDTGISSKAMSIMNSFVNDVFERIAGEASRLAHYNKRSTITSREIQTAVRLLLPGELAKHAVSEGTKAVTKYTSAKARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKLPFQRLVREIAQDFKTDLRFQSSAVMALQEASEAYLVALFEDTNLCAIHAKRVTIMPKDIQLARRIRGERSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGGSGRGKQGGKTRAKAKTRSSRAGLQFPVGRVHRLLRKGNYAERVGAGAPVYLAAVLEYLTAEILELAGNAARDNKKTRIIPRHLQLAVRNDEELNKLLGRVTIAQGGVLPNIQSVLLPKK",
            "SQIPASEQETLVRPKPLLLKLLKSVGAQKDTYTMKEVLFYLGQYIMTKRLYDEKQQHIVYCSNDLLGDLFGVPSFSVKEHRKIYTMIYRNLVVVNQQESSDSGTSVSENSQETFSDLWKLLPEN",
            "KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMSITDCRETGSSKYPNCAYKTTQANKHIIVACEGNPYVPVHFDASV",
            "MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNCNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRCALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL",
            "CGTACG"


        ]
        
        threshold = 0.8  # Define a threshold for similarity

        for i, code in enumerate(protein_codes):
            with self.subTest(code=code):
                result = get_sequence(code)
                similarity = difflib.SequenceMatcher(None, result, expected_sequences[i]).ratio()
                print(f"\nSequence similarity for {code}:\t\t\t {similarity}")
                 
                if similarity < threshold:
                    print(f"Sequence:\t\t\t\t\t {result}")
                    print(f"Expected sequence taken from Fatsa file:\t {expected_sequences[i]}")

                # self.assertGreaterEqual(similarity, threshold, f"Sequence similarity for {code} below threshold. Similarity: {similarity}")

if __name__ == '__main__':
    unittest.main()

